INSERT INTO type (type) VALUES  ('Assault carbine'),
                                ('Assault rilfe'),
                                ('Bolt-action rilfe'),
                                ('Designated marksman rifle'),
                                ('Grenade launcher'),
                                ('Light machine guns'),
                                ('Shotguns'),
                                ('Submachine gun'),
                                ('Pistol'),
                                ('Revolver'),
                                ('Handheld flare'),
                                ('Signal Pistol'),
                                ('Melee weapon'),
                                ('Fragmentation grenade'),
                                ('Smoke grenade'),
                                ('Stun grenade');